### ISSUE TITLE
Pretty print support

### ISSUE THREAD

**Issue by emoon** [fintelia/riscv-decode#1]
Hi,

I wonder if you have any plans on implementing pretty print support? So for example this code

https://github.com/fintelia/riscv-decode/blob/master/src/lib.rs#L314

Would be able to print the instruction in the comment? That would be useful for a disassembler for example.

**Comment by fintelia** [comment]
I don't have plans to add that, but I'd be open to pull requests

**Comment by emoon** [comment]
No need. I did my own thing instead
